config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  get 'complete/:id', to: 'posts#complete', as: 'post_complete'
  get 'incomplete/:id', to: 'posts#incomplete', as: 'post_incomplete'
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def complete
		@post = Post.find(params[:id])
		@post.done = 1
		@post.save
		redirect_to root_path
	end

	def incomplete
		@post = Post.find(params[:id])
		@post.done = 0
		@post.save
		redirect_to root_path
	end

	def create
		@post = Post.new(post_params)
		@post.done = 0
		@post.save
		redirect_to root_path
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	private
		def post_params
			params.require(:post).permit(:body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class='normal'>

<h2>
My Tasks
<%= link_to "Add new", new_post_path, class: 'new'%>
</h2>

<% @posts.each do |post| %>
	<% if post.done == 0 %>
		<p class='notdone'>
		<div class='box'>
		<%= post.body %>
		<br>
		<%= link_to '[done]', post_complete_path(post) %>
		<%= link_to '[x]', post_path(post),method: :delete%>
		</div>
		</p>
	<% end %>
<% end %>

</div>

<div class = 'complete'>

<h3>Complete Tasks</h3>

<% @posts.each do |post| %>
	<% if post.done >= 1 %>
		<p class='done'>
		<div class='box'>
		<%= post.body %>
		<br>
		<%= link_to '[undo]', post_incomplete_path(post) %>
		<%= link_to '[x]', post_path(post),method: :delete%>
		</div>
		</p>
	<% end %>
<% end %>

</div>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= form_for :post, url: posts_path do |f| %>
<p><%= f.text_field :body %></p>
<p><%= f.submit %></p>
<% end %>